import { AriseThemeStyle, ThemeSchemaStruct, WidgetType } from '@/types/section';

const schema: ThemeSchemaStruct = {
  info: {
    name: 'Arise-Pro',
    theme_name: 'Arise-Pro',
    theme_version: '1.3.28',
    theme_author: 'LZC',
    theme_documentation_url: '',
    theme_support_url: '',
    theme_cover_img: '',
    theme_home_pc_preview_img: '',
    theme_home_mobile_preview_img: '',
    theme_pdp_pc_preview_img: '',
    theme_pdp_mobile_preview_img: '',
    theme_type_version: 'OS_2.1',
  },
  blocks: [
    {
      name: 'settings_schema.color.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__0.label',
        },
        {
          id: 'color_page_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_page_background.label',
          default: '#FFFFFF',
        },
        {
          id: 'color_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_text.label',
          default: '#29252C',
        },
        {
          id: 'color_light_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_light_text.label',
          default: '#949494',
        },
        {
          id: 'color_entry_line',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_entry_line.label',
          default: '#EAECEC',
        },
        {
          id: 'color_card_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_card_background.label',
          info: 'settings_schema.color.settings.color_card_background.info',
          default: '',
        },
        {
          id: 'color_card_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_card_text.label',
          info: 'settings_schema.color.settings.color_card_text.info',
          default: '',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__1.label',
        },
        {
          id: 'color_button_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_background.label',
          default: '#74716C',
        },
        {
          id: 'color_button_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_text.label',
          default: '#FFFFFF',
        },
        {
          id: 'color_button_secondary_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_secondary_background.label',
          default: '#FFFFFF',
        },
        {
          id: 'color_button_secondary_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_secondary_text.label',
          default: '#74716C',
        },
        {
          id: 'color_button_secondary_border',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_secondary_border.label',
          default: '#DDDDDD',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__2.label',
        },
        {
          id: 'color_sale',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_sale.label',
          default: '#171F2B',
        },
        {
          id: 'color_discount',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_discount.label',
          default: '#E32619',
        },
        {
          id: 'color_discount_tag_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_discount_tag_background.label',
          default: '#E32619',
        },
        {
          id: 'color_discount_tag_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_discount_tag_text.label',
          default: '#FFFFFF',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__3.label',
        },
        {
          id: 'color_cart_dot',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_cart_dot.label',
          default: '#74716C',
        },
        {
          id: 'color_cart_dot_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_cart_dot_text.label',
          default: '#FFFFFF',
        },
        {
          id: 'color_image_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_image_background.label',
          default: '#F8F8F8',
        },
        {
          id: 'color_image_loading_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_image_loading_background.label',
          default: '#F8F8F8',
        },
        {
          id: 'color_mask',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_mask.label',
          default: '#171717',
        },
        {
          id: 'color_shadow',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_shadow.label',
          default: '',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__4.label',
        },
        {
          id: 'color_scheme_1_bg',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_1_bg.label',
          default: '#FFF8EE',
        },
        {
          id: 'color_scheme_1_gradient',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_1_gradient.label',
          default: '',
        },
        {
          id: 'color_scheme_1_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_1_text.label',
          default: '#2C2924',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__5.label',
        },
        {
          id: 'color_scheme_2_bg',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_2_bg.label',
          default: '#2C2924',
        },
        {
          id: 'color_scheme_2_gradient',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_2_gradient.label',
          default: '',
        },
        {
          id: 'color_scheme_2_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_2_text.label',
          default: '#FFFFFF',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__6.label',
        },
        {
          id: 'color_scheme_3_bg',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_3_bg.label',
          default: '#F4F7FB',
        },
        {
          id: 'color_scheme_3_gradient',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_3_gradient.label',
          default: '',
        },
        {
          id: 'color_scheme_3_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_3_text.label',
          default: '#000000',
        },
      ],
    },
    {
      name: 'settings_schema.font.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.font.settings.group_header__0.label',
        },
        {
          id: 'title_font_family',
          type: WidgetType.font,
          label: 'settings_schema.font.settings.title_font_family.label',
          default: 'Assistant:regular',
        },
        {
          id: 'title_letter_spacing',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.title_letter_spacing.label',
          default: 50,
          min: -75,
          max: 250,
          step: 25,
          unit: '%',
        },
        {
          id: 'title_font_size',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.title_font_size.label',
          default: 34,
          min: 22,
          max: 60,
          unit: 'px',
        },
        {
          id: 'title_line_height',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.title_line_height.label',
          default: 1.2,
          min: 0.8,
          max: 2,
          step: 0.1,
        },
        {
          id: 'title_uppercase',
          type: WidgetType.switch,
          label: 'settings_schema.font.settings.title_uppercase.label',
          default: false,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.font.settings.group_header__1.label',
        },
        {
          id: 'body_font_family',
          type: WidgetType.font,
          label: 'settings_schema.font.settings.body_font_family.label',
          default: 'Assistant:regular',
        },
        {
          id: 'body_letter_spacing',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.body_letter_spacing.label',
          default: 50,
          min: -75,
          max: 250,
          step: 25,
          unit: '%',
        },
        {
          id: 'body_font_size',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.body_font_size.label',
          default: 14,
          min: 12,
          max: 20,
          unit: 'px',
        },
        {
          id: 'body_line_height',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.body_line_height.label',
          default: 1.6,
          min: 1,
          max: 2,
          step: 0.1,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.font.settings.group_header__2.label',
        },
        {
          id: 'header_font',
          type: WidgetType.select,
          label: 'settings_schema.font.settings.header_font.label',
          options: [
            {
              value: 'title',
              label: 'settings_schema.font.settings.header_font.options__0.label',
            },
            {
              value: 'body',
              label: 'settings_schema.font.settings.header_font.options__1.label',
            },
          ],
          default: 'body',
        },
        {
          id: 'header_font_size',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.header_font_size.label',
          default: 14,
          min: 12,
          max: 40,
          unit: 'px',
        },
        {
          id: 'header_text_uppercase',
          type: WidgetType.switch,
          label: 'settings_schema.font.settings.header_text_uppercase.label',
          info: 'settings_schema.font.settings.header_text_uppercase.info',
          default: true,
        },
      ],
    },
    {
      name: 'settings_schema.layout.name',
      settings: [
        {
          id: 'page_width',
          type: WidgetType.range,
          label: 'settings_schema.layout.settings.page_width.label',
          min: 1000,
          max: 1920,
          step: 100,
          unit: 'px',
          default: 1400,
        },
        {
          id: 'section_vertical_gap',
          type: WidgetType.range,
          label: 'settings_schema.layout.settings.section_vertical_gap.label',
          min: 0,
          max: 100,
          step: 4,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.layout.settings.group_header__0.label',
          info: 'settings_schema.layout.settings.group_header__0.info',
        },
        {
          id: 'grid_horizontal_space',
          type: WidgetType.range,
          label: 'settings_schema.layout.settings.grid_horizontal_space.label',
          min: 0,
          max: 40,
          step: 4,
          unit: 'px',
          default: 8,
        },
        {
          id: 'grid_vertical_space',
          type: WidgetType.range,
          label: 'settings_schema.layout.settings.grid_vertical_space.label',
          min: 0,
          max: 40,
          step: 4,
          unit: 'px',
          default: 20,
        },
      ],
    },
    {
      name: 'settings_schema.button.name',
      settings: [
        {
          id: 'btn_hover_animation',
          type: WidgetType.select,
          label: 'settings_schema.button.settings.btn_hover_animation.label',
          default: 'hover_zoom',
          options: [
            {
              value: 'light_sweep',
              label: 'settings_schema.button.settings.btn_hover_animation.options__0.label',
            },
            {
              value: 'overlay_projection',
              label: 'settings_schema.button.settings.btn_hover_animation.options__1.label',
            },
            {
              value: 'hover_zoom',
              label: 'settings_schema.button.settings.btn_hover_animation.options__2.label',
            },
            {
              value: 'fill_right',
              label: 'settings_schema.button.settings.btn_hover_animation.options__3.label',
            },
          ],
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.button.settings.group_header__0.label',
        },
        {
          id: 'btn_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 1,
        },
        {
          id: 'btn_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 100,
        },
        {
          id: 'btn_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.button.settings.group_header__1.label',
        },
        {
          id: 'btn_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'btn_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'btn_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'btn_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.sku.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.sku.settings.group_header__0.label',
        },
        {
          id: 'sku_selector_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.sku.settings.sku_selector_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 1,
        },
        {
          id: 'sku_selector_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.sku.settings.sku_selector_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 55,
        },
        {
          id: 'sku_selector_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.sku.settings.sku_selector_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.sku.settings.group_header__1.label',
        },
        {
          id: 'sku_selector_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.sku.settings.sku_selector_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'sku_selector_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.sku.settings.sku_selector_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'sku_selector_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.sku.settings.sku_selector_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'sku_selector_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.sku.settings.sku_selector_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.input.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.input.settings.group_header__0.label',
        },
        {
          id: 'input_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.input.settings.input_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 1,
        },
        {
          id: 'input_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.input.settings.input_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 55,
        },
        {
          id: 'input_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.input.settings.input_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.input.settings.group_header__1.label',
        },
        {
          id: 'input_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.input.settings.input_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'input_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.input.settings.input_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'input_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.input.settings.input_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'input_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.input.settings.input_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.product.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.product.settings.group_header__0.label',
        },
        {
          id: 'enable_quick_view',
          type: WidgetType.switch,
          label: 'settings_schema.product.settings.enable_quick_view.label',
          default: false,
        },
        {
          id: 'product_add_to_cart',
          type: WidgetType.switch,
          label: 'settings_schema.product.settings.product_add_to_cart.label',
          default: false,
        },
        {
          id: 'enabled_mobile_product_add_to_cart',
          type: WidgetType.switch,
          label: 'settings_schema.product.settings.enabled_mobile_product_add_to_cart.label',
          default: false,
        },
        {
          id: 'product_add_to_cart_pc_style',
          type: WidgetType.select,
          label: 'settings_schema.product.settings.product_add_to_cart_pc_style.label',
          default: 'button',
          options: [
            {
              value: 'icon',
              label: 'settings_schema.product.settings.product_add_to_cart_pc_style.options__0.label',
            },
            {
              value: 'button',
              label: 'settings_schema.product.settings.product_add_to_cart_pc_style.options__1.label',
            },
          ],
        },
        {
          id: 'product_add_to_cart_pc_position',
          type: WidgetType.select,
          options: [
            {
              value: 'center',
              label: 'settings_schema.product.settings.product_add_to_cart_pc_position.options__0.label',
            },
            {
              value: 'under',
              label: 'settings_schema.product.settings.product_add_to_cart_pc_position.options__1.label',
            },
          ],
          label: 'settings_schema.product.settings.product_add_to_cart_pc_position.label',
          info: 'settings_schema.product.settings.product_add_to_cart_pc_position.info',
          default: 'center',
        },
        {
          id: 'product_mobile_quick_add_button_style',
          type: WidgetType.select,
          label: 'settings_schema.product.settings.product_mobile_quick_add_button_style.label',
          options: [
            {
              value: 'icon',
              label: 'settings_schema.product.settings.product_mobile_quick_add_button_style.options__0.label',
            },
            {
              value: 'button',
              label: 'settings_schema.product.settings.product_mobile_quick_add_button_style.options__1.label',
            },
          ],
          default: 'button',
        },
        {
          id: 'product_title_show_type',
          type: WidgetType.select,
          label: 'settings_schema.product.settings.product_title_show_type.label',
          options: [
            {
              value: 'full-display',
              label: 'settings_schema.product.settings.product_title_show_type.options__0.label',
            },
            {
              value: 'display-1-row',
              label: 'settings_schema.product.settings.product_title_show_type.options__1.label',
            },
            {
              value: 'display-2-rows',
              label: 'settings_schema.product.settings.product_title_show_type.options__2.label',
            },
          ],
          default: 'full-display',
        },
        {
          id: 'product_pc_title_show',
          type: WidgetType.switch,
          label: 'settings_schema.product.settings.product_pc_title_show.label',
          default: true,
        },
        {
          id: 'product_mobile_title_show',
          type: WidgetType.switch,
          label: 'settings_schema.product.settings.product_mobile_title_show.label',
          default: true,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.product.settings.group_header__1.label',
          info: 'settings_schema.product.settings.group_header__1.info',
        },
        {
          id: 'enabled_color_swatch',
          type: WidgetType.switch,
          label: 'settings_schema.product.settings.enabled_color_swatch.label',
          default: false,
        },
        {
          id: 'swatch_style',
          type: WidgetType.select,
          label: 'settings_schema.product.settings.swatch_style.label',
          options: [
            {
              value: 'square',
              label: 'settings_schema.product.settings.swatch_style.options__0.label',
            },
            {
              value: 'circle',
              label: 'settings_schema.product.settings.swatch_style.options__1.label',
            },
            {
              value: 'circle_square',
              label: 'settings_schema.product.settings.swatch_style.options__2.label',
            },
          ],
          default: 'square',
        },
        {
          id: 'swatch_max_show',
          type: WidgetType.range,
          label: 'settings_schema.product.settings.swatch_max_show.label',
          max: 6,
          min: 1,
          default: 4,
        },
        {
          id: 'swatch_show_style',
          type: WidgetType.select,
          label: 'settings_schema.product.settings.swatch_show_style.label',
          default: 'show_one_row',
          options: [
            {
              label: 'settings_schema.product.settings.swatch_show_style.options__0.label',
              value: 'show_one_row',
            },
            {
              label: 'settings_schema.product.settings.swatch_show_style.options__1.label',
              value: 'horizontal_slide',
            },
            {
              label: 'settings_schema.product.settings.swatch_show_style.options__2.label',
              value: 'tiling',
            },
          ],
        },
        {
          id: 'swatch_size',
          type: WidgetType.select,
          label: 'settings_schema.product.settings.swatch_size.label',
          default: 18,
          options: [
            {
              label: 'settings_schema.product.settings.swatch_size.options__0.label',
              value: 14,
            },
            {
              label: 'settings_schema.product.settings.swatch_size.options__1.label',
              value: 16,
            },
            {
              label: 'settings_schema.product.settings.swatch_size.options__2.label',
              value: 18,
            },
          ],
        },
        {
          id: 'product_discount',
          type: WidgetType.switch,
          label: 'settings_schema.product.settings.product_discount.label',
          default: true,
        },
        {
          id: 'product_discount_tag_style',
          type: WidgetType.select,
          label: 'settings_schema.product.settings.product_discount_tag_style.label',
          options: [
            {
              value: 'sale',
              label: 'settings_schema.product.settings.product_discount_tag_style.options__0.label',
            },
            {
              value: 'save',
              label: 'settings_schema.product.settings.product_discount_tag_style.options__1.label',
            },
          ],
          default: 'save',
        },
        {
          id: 'product_discount_style',
          type: WidgetType.select,
          label: 'settings_schema.product.settings.product_discount_style.label',
          info: 'settings_schema.product.settings.product_discount_style.info',
          options: [
            {
              value: 'number',
              label: 'settings_schema.product.settings.product_discount_style.options__0.label',
            },
            {
              value: 'ratio',
              label: 'settings_schema.product.settings.product_discount_style.options__1.label',
            },
          ],
          default: 'number',
        },
        {
          id: 'product_discount_position',
          type: WidgetType.select,
          label: 'settings_schema.product.settings.product_discount_position.label',
          options: [
            {
              value: 'left_top',
              label: 'settings_schema.product.settings.product_discount_position.options__0.label',
            },
            {
              value: 'right_top',
              label: 'settings_schema.product.settings.product_discount_position.options__1.label',
            },
            {
              value: 'left_bottom',
              label: 'settings_schema.product.settings.product_discount_position.options__2.label',
            },
            {
              value: 'right_bottom',
              label: 'settings_schema.product.settings.product_discount_position.options__3.label',
            },
          ],
          default: 'left_bottom',
        },
        {
          id: 'product_discount_radius',
          type: WidgetType.range,
          label: 'settings_schema.product.settings.product_discount_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 40,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.product.settings.group_header__2.label',
          info: 'settings_schema.product.settings.group_header__2.info',
        },
        {
          type: WidgetType.select,
          id: 'product_card_price_show_type',
          label: 'settings_schema.product.settings.product_card_price_show_type.label',
          info: 'settings_schema.product.settings.product_card_price_show_type.info',
          options: [
            {
              value: 'lowest_price',
              label: 'settings_schema.product.settings.product_card_price_show_type.options__0.label',
            },
            {
              value: 'price_interval',
              label: 'settings_schema.product.settings.product_card_price_show_type.options__1.label',
            },
            {
              value: 'from_lowest_price',
              label: 'settings_schema.product.settings.product_card_price_show_type.options__2.label',
            },
          ],
          default: 'lowest_price',
        },
      ],
    },
    {
      name: 'settings_schema.product_card.name',
      settings: [
        {
          id: 'product_card_style',
          type: WidgetType.select,
          label: 'settings_schema.product_card.settings.product_card_style.label',
          options: [
            {
              value: 'normal',
              label: 'settings_schema.product_card.settings.product_card_style.options__0.label',
            },
            {
              value: 'card',
              label: 'settings_schema.product_card.settings.product_card_style.options__1.label',
            },
          ],
          default: 'normal',
        },
        {
          id: 'product_card_image_padding',
          type: WidgetType.range,
          label: 'settings_schema.product_card.settings.product_card_image_padding.label',
          info: 'settings_schema.product_card.settings.product_card_image_padding.info',
          min: 0,
          max: 20,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'product_card_content_align',
          type: WidgetType.select,
          label: 'settings_schema.product_card.settings.product_card_content_align.label',
          default: 'left',
          options: [
            {
              value: 'left',
              label: 'settings_schema.product_card.settings.product_card_content_align.options__0.label',
            },
            {
              value: 'center',
              label: 'settings_schema.product_card.settings.product_card_content_align.options__1.label',
            },
          ],
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.product_card.settings.group_header__0.label',
        },
        {
          id: 'product_card_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.product_card.settings.product_card_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 0,
        },
        {
          id: 'product_card_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.product_card.settings.product_card_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 10,
        },
        {
          id: 'product_card_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.product_card.settings.product_card_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.product_card.settings.group_header__1.label',
        },
        {
          id: 'product_card_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.product_card.settings.product_card_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'product_card_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.product_card.settings.product_card_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'product_card_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.product_card.settings.product_card_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'product_card_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.product_card.settings.product_card_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.collection_card.name',
      settings: [
        {
          id: 'collection_card_style',
          type: WidgetType.select,
          label: 'settings_schema.collection_card.settings.collection_card_style.label',
          options: [
            {
              value: 'normal',
              label: 'settings_schema.collection_card.settings.collection_card_style.options__0.label',
            },
            {
              value: 'card',
              label: 'settings_schema.collection_card.settings.collection_card_style.options__1.label',
            },
          ],
          default: 'normal',
        },
        {
          id: 'collection_card_image_padding',
          type: WidgetType.range,
          label: 'settings_schema.collection_card.settings.collection_card_image_padding.label',
          info: 'settings_schema.collection_card.settings.collection_card_image_padding.info',
          min: 0,
          max: 20,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'collection_card_content_align',
          type: WidgetType.select,
          label: 'settings_schema.collection_card.settings.collection_card_content_align.label',
          default: 'center',
          options: [
            {
              value: 'left',
              label: 'settings_schema.collection_card.settings.collection_card_content_align.options__0.label',
            },
            {
              value: 'center',
              label: 'settings_schema.collection_card.settings.collection_card_content_align.options__1.label',
            },
          ],
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.collection_card.settings.group_header__0.label',
        },
        {
          id: 'collection_card_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.collection_card.settings.collection_card_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 0,
        },
        {
          id: 'collection_card_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.collection_card.settings.collection_card_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 10,
        },
        {
          id: 'collection_card_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.collection_card.settings.collection_card_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.collection_card.settings.group_header__1.label',
        },
        {
          id: 'collection_card_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.collection_card.settings.collection_card_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'collection_card_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.collection_card.settings.collection_card_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'collection_card_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.collection_card.settings.collection_card_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'collection_card_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.collection_card.settings.collection_card_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.blog_card.name',
      settings: [
        {
          id: 'blog_card_style',
          type: WidgetType.select,
          label: 'settings_schema.blog_card.settings.blog_card_style.label',
          options: [
            {
              value: 'normal',
              label: 'settings_schema.blog_card.settings.blog_card_style.options__0.label',
            },
            {
              value: 'card',
              label: 'settings_schema.blog_card.settings.blog_card_style.options__1.label',
            },
          ],
          default: 'normal',
        },
        {
          id: 'blog_card_image_padding',
          type: WidgetType.range,
          label: 'settings_schema.blog_card.settings.blog_card_image_padding.label',
          info: 'settings_schema.blog_card.settings.blog_card_image_padding.info',
          min: 0,
          max: 20,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'blog_card_content_align',
          type: WidgetType.select,
          label: 'settings_schema.blog_card.settings.blog_card_content_align.label',
          default: 'center',
          options: [
            {
              value: 'left',
              label: 'settings_schema.blog_card.settings.blog_card_content_align.options__0.label',
            },
            {
              value: 'center',
              label: 'settings_schema.blog_card.settings.blog_card_content_align.options__1.label',
            },
          ],
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.blog_card.settings.group_header__0.label',
        },
        {
          id: 'blog_card_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.blog_card.settings.blog_card_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 0,
        },
        {
          id: 'blog_card_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.blog_card.settings.blog_card_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 10,
        },
        {
          id: 'blog_card_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.blog_card.settings.blog_card_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.blog_card.settings.group_header__1.label',
        },
        {
          id: 'blog_card_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.blog_card.settings.blog_card_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'blog_card_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.blog_card.settings.blog_card_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'blog_card_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.blog_card.settings.blog_card_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'blog_card_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.blog_card.settings.blog_card_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.other_card.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.other_card.settings.group_header__0.label',
        },
        {
          id: 'card_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.other_card.settings.card_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 0,
        },
        {
          id: 'card_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.other_card.settings.card_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 10,
        },
        {
          id: 'card_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.other_card.settings.card_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.other_card.settings.group_header__1.label',
        },
        {
          id: 'card_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.other_card.settings.card_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'card_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.other_card.settings.card_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'card_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.other_card.settings.card_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'card_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.other_card.settings.card_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.content.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.content.settings.group_header__0.label',
        },
        {
          id: 'content_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.content.settings.content_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 0,
        },
        {
          id: 'content_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.content.settings.content_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'content_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.content.settings.content_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.content.settings.group_header__1.label',
        },
        {
          id: 'content_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.content.settings.content_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'content_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.content.settings.content_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'content_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.content.settings.content_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'content_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.content.settings.content_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.media_files.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.media_files.settings.group_header__0.label',
        },
        {
          id: 'media_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.media_files.settings.media_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 0,
        },
        {
          id: 'media_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.media_files.settings.media_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 5,
        },
        {
          id: 'media_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.media_files.settings.media_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.media_files.settings.group_header__1.label',
        },
        {
          id: 'media_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.media_files.settings.media_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'media_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.media_files.settings.media_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'media_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.media_files.settings.media_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'media_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.media_files.settings.media_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.dropdown_menu.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.dropdown_menu.settings.group_header__0.label',
        },
        {
          id: 'menu_modal_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.dropdown_menu.settings.menu_modal_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 1,
        },
        {
          id: 'menu_modal_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.dropdown_menu.settings.menu_modal_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 10,
        },
        {
          id: 'menu_modal_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.dropdown_menu.settings.menu_modal_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.dropdown_menu.settings.group_header__1.label',
        },
        {
          id: 'menu_modal_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.dropdown_menu.settings.menu_modal_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'menu_modal_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.dropdown_menu.settings.menu_modal_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'menu_modal_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.dropdown_menu.settings.menu_modal_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'menu_modal_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.dropdown_menu.settings.menu_modal_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.drawer.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.drawer.settings.group_header__0.label',
        },
        {
          id: 'drawer_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.drawer.settings.drawer_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 1,
        },
        {
          id: 'drawer_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.drawer.settings.drawer_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 10,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.drawer.settings.group_header__1.label',
        },
        {
          id: 'drawer_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.drawer.settings.drawer_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'drawer_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.drawer.settings.drawer_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'drawer_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.drawer.settings.drawer_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'drawer_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.drawer.settings.drawer_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.cart.name',
      settings: [
        {
          id: 'cart_type',
          type: WidgetType.select,
          label: 'settings_schema.cart.settings.cart_type.label',
          options: [
            {
              value: 'drawer',
              label: 'settings_schema.cart.settings.cart_type.options__0.label',
            },
            {
              value: 'page',
              label: 'settings_schema.cart.settings.cart_type.options__1.label',
            },
            {
              value: 'notification',
              label: 'settings_schema.cart.settings.cart_type.options__2.label',
            },
            {
              value: 'cart_remind',
              label: 'settings_schema.cart.settings.cart_type.options__3.label',
            },
          ],
          default: 'drawer',
        },
        {
          id: 'cart_continue_url',
          type: WidgetType.url,
          label: 'settings_schema.cart.settings.cart_continue_url.label',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.cart.settings.group_header__0.label',
        },
        {
          type: WidgetType.text,
          id: 'cart_empty_recommend_title',
          label: 'settings_schema.cart.settings.cart_empty_recommend_title.label',
          default: 'You May Also Like',
        },
        {
          type: 'collection_picker',
          id: 'cart_empty_recommend_collection',
          label: 'settings_schema.cart.settings.cart_empty_recommend_collection.label',
        },
        {
          type: WidgetType.range,
          id: 'cart_empty_recommend_product_to_show',
          min: 4,
          max: 12,
          step: 1,
          default: 12,
          label: 'settings_schema.cart.settings.cart_empty_recommend_product_to_show.label',
        },
        {
          id: 'cart_empty_recommend_product_image_ratio',
          type: WidgetType.select,
          label: 'settings_schema.cart.settings.cart_empty_recommend_product_image_ratio.label',
          options: [
            {
              value: 'adapt',
              label: 'settings_schema.cart.settings.cart_empty_recommend_product_image_ratio.options__0.label',
            },
            {
              value: '100',
              label: 'settings_schema.cart.settings.cart_empty_recommend_product_image_ratio.options__1.label',
            },
            { value: '133.33', label: '3:4' },
            {
              value: '75',
              label: 'settings_schema.cart.settings.cart_empty_recommend_product_image_ratio.options__3.label',
            },
            {
              value: '150',
              label: 'settings_schema.cart.settings.cart_empty_recommend_product_image_ratio.options__4.label',
            },
          ],
          default: '150',
        },
        {
          id: 'cart_empty_recommend_product_image_fill_type',
          type: WidgetType.select,
          label: 'settings_schema.cart.settings.cart_empty_recommend_product_image_fill_type.label',
          options: [
            {
              value: 'contain',
              label: 'settings_schema.cart.settings.cart_empty_recommend_product_image_fill_type.options__0.label',
            },
            {
              value: 'cover',
              label: 'settings_schema.cart.settings.cart_empty_recommend_product_image_fill_type.options__1.label',
            },
          ],
          default: 'contain',
        },
      ],
    },
    {
      name: 'settings_schema.checkout.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.checkout.settings.group_header__0.label',
        },
        {
          id: 'co_banner_pc_img',
          type: 'image_picker',
          label: 'settings_schema.checkout.settings.co_banner_pc_img.label',
          default: {},
        },
        {
          id: 'co_banner_phone_img',
          type: 'image_picker',
          label: 'settings_schema.checkout.settings.co_banner_phone_img.label',
          info: 'settings_schema.checkout.settings.co_banner_phone_img.info',
          default: {},
        },
        {
          id: 'co_banner_pc_height',
          type: WidgetType.select,
          label: 'settings_schema.checkout.settings.co_banner_pc_height.label',
          options: [
            {
              label: 'settings_schema.checkout.settings.co_banner_pc_height.options__0.label',
              value: 'natural',
            },
            {
              value: 'high',
              label: 'settings_schema.checkout.settings.co_banner_pc_height.options__1.label',
            },
            {
              value: 'low',
              label: 'settings_schema.checkout.settings.co_banner_pc_height.options__2.label',
            },
          ],
          default: 'low',
        },
        {
          id: 'co_banner_phone_height',
          type: WidgetType.select,
          label: 'settings_schema.checkout.settings.co_banner_phone_height.label',
          options: [
            {
              label: 'settings_schema.checkout.settings.co_banner_phone_height.options__0.label',
              value: 'natural',
            },
            {
              value: 'high',
              label: 'settings_schema.checkout.settings.co_banner_phone_height.options__1.label',
            },
            {
              value: 'low',
              label: 'settings_schema.checkout.settings.co_banner_phone_height.options__2.label',
            },
          ],
          default: 'low',
        },
        {
          id: 'co_banner_img_show',
          type: WidgetType.select,
          label: 'settings_schema.checkout.settings.co_banner_img_show.label',
          options: [
            {
              label: 'settings_schema.checkout.settings.co_banner_img_show.options__0.label',
              value: 'top',
            },
            {
              value: 'center',
              label: 'settings_schema.checkout.settings.co_banner_img_show.options__1.label',
            },
            {
              value: 'bottom',
              label: 'settings_schema.checkout.settings.co_banner_img_show.options__2.label',
            },
          ],
          default: 'center',
        },
        {
          id: 'co_full_screen',
          type: WidgetType.switch,
          label: 'settings_schema.checkout.settings.co_full_screen.label',
          default: true,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.checkout.settings.group_header__1.label',
        },
        {
          id: 'co_checkout_image',
          type: 'image_picker',
          label: 'settings_schema.checkout.settings.co_checkout_image.label',
          default: {},
        },
        {
          id: 'co_logo_size',
          type: WidgetType.select,
          label: 'settings_schema.checkout.settings.co_logo_size.label',
          options: [
            {
              label: 'settings_schema.checkout.settings.co_logo_size.options__0.label',
              value: 'small',
            },
            {
              value: 'medium',
              label: 'settings_schema.checkout.settings.co_logo_size.options__1.label',
            },
            {
              value: 'large',
              label: 'settings_schema.checkout.settings.co_logo_size.options__2.label',
            },
          ],
          default: 'medium',
        },
        {
          id: 'co_logo_position',
          type: WidgetType.select,
          label: 'settings_schema.checkout.settings.co_logo_position.label',
          options: [
            {
              label: 'settings_schema.checkout.settings.co_logo_position.options__0.label',
              value: 'left',
            },
            {
              value: 'center',
              label: 'settings_schema.checkout.settings.co_logo_position.options__1.label',
            },
            {
              value: 'right',
              label: 'settings_schema.checkout.settings.co_logo_position.options__2.label',
            },
          ],
          default: 'left',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.checkout.settings.group_header__2.label',
        },
        {
          id: 'co_bg_image',
          type: 'image_picker',
          label: 'settings_schema.checkout.settings.co_bg_image.label',
          default: {},
        },
        {
          id: 'co_background_color',
          type: 'color',
          label: 'settings_schema.checkout.settings.co_background_color.label',
          default: '#FFFFFF',
        },
        {
          id: 'co_form_bg_color',
          type: WidgetType.select,
          label: 'settings_schema.checkout.settings.co_form_bg_color.label',
          options: [
            {
              label: 'settings_schema.checkout.settings.co_form_bg_color.options__0.label',
              value: 'white',
            },
            {
              value: 'transparent',
              label: 'settings_schema.checkout.settings.co_form_bg_color.options__1.label',
            },
          ],
          default: 'white',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.checkout.settings.group_header__3.label',
        },
        {
          id: 'co_order_bg_image',
          type: 'image_picker',
          label: 'settings_schema.checkout.settings.co_order_bg_image.label',
          default: {},
        },
        {
          id: 'co_order_background_color',
          type: 'color',
          label: 'settings_schema.checkout.settings.co_order_background_color.label',
          default: '#FAFAFA',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.checkout.settings.group_header__4.label',
        },
        {
          id: 'co_type_title_font',
          type: 'font_lib_picker',
          label: 'settings_schema.checkout.settings.co_type_title_font.label',
          options: [
            'Open Sans',
            'Lato',
            'Oswald',
            'Noto Sans Display',
            'Roboto',
            'Raleway',
            'Fjalla One',
            'Abel',
            'Source Sans Pro',
            'EB Garamond',
            'PT Serif',
            'Lora',
            'Arvo',
            'Playfair Display',
            'Vidaloka',
            'Glegoo',
            'Playball',
            'Lobster Two',
          ],
          default: { lib: 'system', value: 'Helvetica Neue / Arial' },
        },
        {
          id: 'co_type_body_font',
          type: 'font_lib_picker',
          label: 'settings_schema.checkout.settings.co_type_body_font.label',
          options: [
            'Open Sans',
            'Lato',
            'Oswald',
            'Noto Sans Display',
            'Roboto',
            'Raleway',
            'Fjalla One',
            'Abel',
            'Source Sans Pro',
            'EB Garamond',
            'PT Serif',
            'Lora',
            'Arvo',
            'Playfair Display',
            'Vidaloka',
            'Glegoo',
            'Playball',
            'Lobster Two',
          ],
          default: { lib: 'system', value: 'Helvetica Neue / Arial' },
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.checkout.settings.group_header__5.label',
        },
        {
          id: 'co_color_btn_bg',
          type: 'color',
          label: 'settings_schema.checkout.settings.co_color_btn_bg.label',
          default: '#276EAF',
        },
        {
          id: 'co_color_err_color',
          type: 'color',
          label: 'settings_schema.checkout.settings.co_color_err_color.label',
          info: 'settings_schema.checkout.settings.co_color_err_color.info',
          default: '#F04949',
        },
        {
          id: 'co_color_msg_color',
          type: 'color',
          label: 'settings_schema.checkout.settings.co_color_msg_color.label',
          info: 'settings_schema.checkout.settings.co_color_msg_color.info',
          default: '#276EAF',
        },
      ],
    },
    {
      name: 'settings_schema.media_sosial.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.media_sosial.settings.group_header__0.label',
          info: 'settings_schema.media_sosial.settings.group_header__0.info',
        },
        {
          id: 'show_official_icon',
          type: WidgetType.switch,
          label: 'settings_schema.media_sosial.settings.show_official_icon.label',
          default: false,
        },
        {
          id: 'social_facebook_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_facebook_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_twitter_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_twitter_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_pinterest_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_pinterest_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_instagram_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_instagram_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_snapchat_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_snapchat_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_tiktok_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_tiktok_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_youtube_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_youtube_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_vimeo_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_vimeo_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_tumblr_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_tumblr_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_linkedin_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_linkedin_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_whatsapp_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_whatsapp_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_line_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_line_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          id: 'social_kakao_link',
          type: WidgetType.text,
          label: 'settings_schema.media_sosial.settings.social_kakao_link.label',
          default: '',
          placeholder: 'http://',
          format: 'uri',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.media_sosial.settings.group_header__1.label',
          info: 'settings_schema.media_sosial.settings.group_header__1.info',
        },
        {
          id: 'show_official_share_icon',
          type: WidgetType.switch,
          label: 'settings_schema.media_sosial.settings.show_official_share_icon.label',
          default: false,
        },
        {
          id: 'show_social_name',
          type: WidgetType.switch,
          label: 'settings_schema.media_sosial.settings.show_social_name.label',
          default: true,
        },
        {
          id: 'share_to_facebook',
          type: WidgetType.switch,
          label: 'settings_schema.media_sosial.settings.share_to_facebook.label',
          default: true,
        },
        {
          id: 'share_to_twitter',
          type: WidgetType.switch,
          label: 'settings_schema.media_sosial.settings.share_to_twitter.label',
          default: true,
        },
        {
          id: 'share_to_pinterest',
          type: WidgetType.switch,
          label: 'settings_schema.media_sosial.settings.share_to_pinterest.label',
          default: true,
        },
        {
          id: 'share_to_line',
          type: WidgetType.switch,
          label: 'settings_schema.media_sosial.settings.share_to_line.label',
          default: true,
        },
        {
          id: 'share_to_whatsapp',
          type: WidgetType.switch,
          label: 'settings_schema.media_sosial.settings.share_to_whatsapp.label',
          default: true,
        },
        {
          id: 'share_to_tumblr',
          type: WidgetType.switch,
          label: 'settings_schema.media_sosial.settings.share_to_tumblr.label',
          default: true,
        },
      ],
    },
    {
      name: 'settings_schema.search_behavior.name',
      settings: [
        {
          id: 'show_search_goods_price',
          type: WidgetType.switch,
          label: 'settings_schema.search_behavior.settings.show_search_goods_price.label',
          default: true,
        },
      ],
    },
    {
      name: 'settings_schema.breadcrumb.name',
      settings: [
        {
          id: 'show_breadcrumb',
          type: WidgetType.switch,
          label: 'settings_schema.breadcrumb.settings.show_breadcrumb.label',
          default: true,
        },
      ],
    },
    {
      name: 'settings_schema.favicon.name',
      settings: [
        {
          id: 'favicon_image',
          type: WidgetType.image_picker,
          label: 'settings_schema.favicon.settings.favicon_image.label',
          info: 'settings_schema.favicon.settings.favicon_image.info',
          default: '',
        },
      ],
    },
  ],
  presets: [
    {
      type: AriseThemeStyle.Default,
      name: 'settings_schema.theme.default',
      settings: {
        color_page_background: '#ffffff',
        color_text: '#3d2f16',
        color_light_text: '#686868',
        color_sale: '#3d2f16',
        color_discount: '#b19460',
        color_entry_line: '#f4f4ef',
        color_card_background: '#f9f9f6',
        color_card_text: '#3d2f16',
        color_button_background: '#b19460',
        color_button_text: '#ffffff',
        color_button_secondary_background: '#ffffff',
        color_button_secondary_text: '#3d2f16',
        color_button_secondary_border: '#3d2f16',
        color_discount_tag_background: '#b19460',
        color_discount_tag_text: '#FFFFFF',
        color_cart_dot: '#b19460',
        color_cart_dot_text: '#FFFFFF',
        color_image_background: '#f4f4ef',
        color_image_loading_background: '#f4f4ef',
        color_mask: '#3d2f16',
        color_scheme_1_bg: '#f4f4ef',
        color_scheme_1_text: '#3d2f16',
        color_scheme_2_bg: '#f4f4ef',
        color_scheme_2_text: '#3d2f16',
        color_scheme_3_bg: '#ebe9d7',
        color_scheme_3_text: '#b19460',
        title_font_family: 'Work Sans:regular',
        title_letter_spacing: 0,
        title_font_size: 60,
        title_line_height: 1.2,
        title_uppercase: true,
        body_font_family: 'Inter:300',
        body_letter_spacing: 25,
        body_font_size: 16,
        body_line_height: 1.6,
        header_font: 'body',
        header_font_size: 16,
        header_text_uppercase: true,
        page_width: 1500,
        section_vertical_gap: 0,
        grid_horizontal_space: 20,
        grid_vertical_space: 20,
        btn_border_radius: 0,
        btn_border_thickness: 1,
        btn_border_opacity: 100,
        btn_shadow_offset_x: 0,
        btn_shadow_offset_y: 4,
        btn_shadow_blur: 5,
        btn_shadow_opacity: 0,
        input_border_thickness: 1,
        input_border_opacity: 55,
        input_border_radius: 0,
        input_shadow_opacity: 0,
        input_shadow_offset_x: 0,
        input_shadow_offset_y: 4,
        input_shadow_blur: 5,
        sku_selector_border_radius: 0,
        sku_selector_border_thickness: 1,
        sku_selector_border_opacity: 55,
        sku_selector_shadow_opacity: 0,
        sku_selector_shadow_offset_x: 0,
        sku_selector_shadow_offset_y: 4,
        sku_selector_shadow_blur: 5,
        content_border_thickness: 0,
        content_border_opacity: 0,
        content_border_radius: 0,
        content_shadow_opacity: 0,
        content_shadow_offset_x: 0,
        content_shadow_offset_y: 4,
        content_shadow_blur: 5,
        media_border_thickness: 0,
        media_border_opacity: 5,
        media_border_radius: 0,
        media_shadow_opacity: 0,
        media_shadow_offset_x: 0,
        media_shadow_offset_y: 4,
        media_shadow_blur: 5,
        menu_modal_border_thickness: 1,
        menu_modal_border_opacity: 10,
        menu_modal_border_radius: 0,
        menu_modal_shadow_opacity: 0,
        menu_modal_shadow_offset_x: 0,
        menu_modal_shadow_offset_y: 4,
        menu_modal_shadow_blur: 5,
        drawer_border_thickness: 1,
        drawer_border_opacity: 10,
        drawer_shadow_offset_x: 0,
        drawer_shadow_offset_y: 4,
        drawer_shadow_blur: 5,
        drawer_shadow_opacity: 0,
        card_border_thickness: 0,
        card_border_opacity: 10,
        card_border_radius: 0,
        card_shadow_offset_x: 0,
        card_shadow_offset_y: 4,
        card_shadow_blur: 5,
        card_shadow_opacity: 0,
        product_card_style: 'card',
        product_card_image_padding: 0,
        product_card_border_thickness: 0,
        product_card_border_opacity: 5,
        product_card_border_radius: 0,
        product_card_shadow_offset_x: 8,
        product_card_shadow_offset_y: 6,
        product_card_shadow_blur: 0,
        product_card_shadow_opacity: 0,
        collection_card_style: 'normal',
        collection_card_image_padding: 0,
        collection_card_content_align: 'center',
        collection_card_border_thickness: 0,
        collection_card_border_opacity: 10,
        collection_card_border_radius: 0,
        collection_card_shadow_offset_x: 0,
        collection_card_shadow_offset_y: 4,
        collection_card_shadow_blur: 5,
        collection_card_shadow_opacity: 0,
        blog_card_style: 'card',
        blog_card_image_padding: 0,
        blog_card_content_align: 'center',
        blog_card_border_thickness: 0,
        blog_card_border_opacity: 10,
        blog_card_border_radius: 0,
        blog_card_shadow_offset_x: 0,
        blog_card_shadow_offset_y: 4,
        blog_card_shadow_blur: 5,
        blog_card_shadow_opacity: 0,
        product_discount: true,
        product_discount_tag_style: 'save',
        product_discount_style: 'number',
        product_add_to_cart_pc_position: 'under',
        enabled_mobile_product_add_to_cart: true,
        product_mobile_quick_add_button_style: 'button',
        product_discount_position: 'left_top',
        product_discount_radius: 0,
        product_card_price_show_type: 'lowest_price',
        product_add_to_cart: false,
        product_card_content_align: 'center',
        enable_quick_view: false,
        product_title_show_type: 'full-display',
        product_mobile_title_show: true,
        enabled_color_swatch: true,
        swatch_max_show: 5,
        swatch_style: 'circle',
        cart_type: 'cart_remind',
        cart_empty_recommend_title: 'You May Also Like',
        cart_empty_recommend_collection: '',
        cart_empty_recommend_product_to_show: 6,
        cart_empty_recommend_product_image_ratio: '133.33',
        cart_empty_recommend_product_image_fill_type: 'contain',
        social_facebook_link: '',
        social_twitter_link: '',
        social_pinterest_link: '',
        social_instagram_link: '',
        social_snapchat_link: '',
        social_tiktok_link: '',
        social_youtube_link: '',
        social_vimeo_link: '',
        social_tumblr_link: '',
        social_linkedin_link: '',
        social_whatsapp_link: '',
        social_line_link: '',
        social_kakao_link: '',
        favicon_image: '',
        show_official_icon: false,
        show_official_share_icon: false,
        show_social_name: false,
        share_to_facebook: true,
        share_to_twitter: true,
        share_to_pinterest: true,
        share_to_line: true,
        share_to_whatsapp: true,
        share_to_tumblr: true,
        show_breadcrumb: true,
        co_type_title_font: {
          lib: 'system',
          value: 'System',
        },
        co_type_body_font: {
          lib: 'system',
          value: 'System',
        },
        color_scheme_1_gradient: '',
        color_scheme_2_gradient: '',
        color_scheme_3_gradient: '',
        swatch_show_style: 'show_one_row',
        swatch_size: 18,
        show_search_goods_price: true,
        product_add_to_cart_pc_style: 'button',
        product_pc_title_show: true,
        color_shadow: '',
        btn_hover_animation: 'light_sweep',
      },
    },
    {
      type: AriseThemeStyle.Food,
      name: 'settings_schema.theme.food',
      settings: {
        color_page_background: '#f8edde',
        color_text: '#ff0f00',
        color_light_text: '#529c50',
        color_sale: '#ff0f00',
        color_discount: '#529c50',
        color_entry_line: '#f8edde',
        color_card_background: '',
        color_card_text: '',
        color_button_background: '#ff0f00',
        color_button_text: '#f8edde',
        color_button_secondary_background: '#f8edde',
        color_button_secondary_text: '#ff0f00',
        color_button_secondary_border: '#e02020',
        color_discount_tag_background: '#529c50',
        color_discount_tag_text: '#f8edde',
        color_cart_dot: '#ff0f00',
        color_cart_dot_text: '#f8edde',
        color_image_background: 'rgba(0,0,0,0)',
        color_image_loading_background: '#ff0f00',
        color_mask: '#ff0f00',
        color_shadow: '',
        color_scheme_1_bg: '#ff0f00',
        color_scheme_1_text: '#f8edde',
        color_scheme_2_bg: '#f8edde',
        color_scheme_2_text: '#ff0f00',
        color_scheme_3_bg: '#ff0f00',
        color_scheme_3_text: '#ffe605',
        title_font_family: 'Viaoda Libre',
        title_letter_spacing: 50,
        title_font_size: 60,
        title_line_height: 1.2,
        title_uppercase: false,
        body_font_family: 'Raleway',
        body_letter_spacing: 50,
        body_font_size: 14,
        body_line_height: 1.6,
        header_font: 'title',
        header_font_size: 14,
        header_text_uppercase: true,
        page_width: 1920,
        section_vertical_gap: 0,
        grid_horizontal_space: 8,
        grid_vertical_space: 20,
        btn_border_radius: 0,
        btn_hover_animation: 'hover_zoom',
        btn_border_thickness: 1,
        btn_border_opacity: 100,
        btn_shadow_offset_x: 0,
        btn_shadow_offset_y: 4,
        btn_shadow_blur: 5,
        btn_shadow_opacity: 0,
        input_border_thickness: 1,
        input_border_opacity: 55,
        input_border_radius: 0,
        input_shadow_opacity: 0,
        input_shadow_offset_x: 0,
        input_shadow_offset_y: 4,
        input_shadow_blur: 5,
        sku_selector_border_radius: 0,
        sku_selector_border_thickness: 1,
        sku_selector_border_opacity: 55,
        sku_selector_shadow_opacity: 0,
        sku_selector_shadow_offset_x: 0,
        sku_selector_shadow_offset_y: 4,
        sku_selector_shadow_blur: 5,
        content_border_thickness: 0,
        content_border_opacity: 0,
        content_border_radius: 0,
        content_shadow_opacity: 0,
        content_shadow_offset_x: 0,
        content_shadow_offset_y: 4,
        content_shadow_blur: 5,
        media_border_thickness: 0,
        media_border_opacity: 5,
        media_border_radius: 0,
        media_shadow_opacity: 0,
        media_shadow_offset_x: 0,
        media_shadow_offset_y: 4,
        media_shadow_blur: 5,
        menu_modal_border_thickness: 1,
        menu_modal_border_opacity: 10,
        menu_modal_border_radius: 0,
        menu_modal_shadow_opacity: 0,
        menu_modal_shadow_offset_x: 0,
        menu_modal_shadow_offset_y: 4,
        menu_modal_shadow_blur: 5,
        drawer_border_thickness: 1,
        drawer_border_opacity: 10,
        drawer_shadow_offset_x: 0,
        drawer_shadow_offset_y: 4,
        drawer_shadow_blur: 5,
        drawer_shadow_opacity: 0,
        card_border_thickness: 0,
        card_border_opacity: 10,
        card_border_radius: 0,
        card_shadow_offset_x: 0,
        card_shadow_offset_y: 4,
        card_shadow_blur: 5,
        card_shadow_opacity: 0,
        product_card_style: 'normal',
        product_card_image_padding: 0,
        product_card_border_thickness: 0,
        product_card_border_opacity: 10,
        product_card_border_radius: 0,
        product_card_shadow_offset_x: 0,
        product_card_shadow_offset_y: 0,
        product_card_shadow_blur: 5,
        product_card_shadow_opacity: 0,
        collection_card_style: 'normal',
        collection_card_image_padding: 0,
        collection_card_content_align: 'center',
        collection_card_border_thickness: 0,
        collection_card_border_opacity: 10,
        collection_card_border_radius: 0,
        collection_card_shadow_offset_x: 0,
        collection_card_shadow_offset_y: 4,
        collection_card_shadow_blur: 5,
        collection_card_shadow_opacity: 0,
        blog_card_style: 'normal',
        blog_card_image_padding: 0,
        blog_card_content_align: 'center',
        blog_card_border_thickness: 0,
        blog_card_border_opacity: 10,
        blog_card_border_radius: 0,
        blog_card_shadow_offset_x: 0,
        blog_card_shadow_offset_y: 4,
        blog_card_shadow_blur: 5,
        blog_card_shadow_opacity: 0,
        product_discount: true,
        product_discount_tag_style: 'save',
        product_discount_style: 'number',
        product_add_to_cart_pc_position: 'center',
        product_add_to_cart_pc_style: 'button',
        enabled_mobile_product_add_to_cart: false,
        product_mobile_quick_add_button_style: 'button',
        product_discount_position: 'left_bottom',
        product_discount_radius: 0,
        product_card_price_show_type: 'lowest_price',
        product_add_to_cart: true,
        product_card_content_align: 'left',
        enable_quick_view: true,
        product_title_show_type: 'full-display',
        product_mobile_title_show: true,
        product_pc_title_show: true,
        enabled_color_swatch: false,
        swatch_max_show: 4,
        swatch_style: 'square',
        cart_type: 'drawer',
        cart_empty_recommend_title: 'You May Also Like',
        cart_empty_recommend_collection: '',
        cart_empty_recommend_product_to_show: 12,
        cart_empty_recommend_product_image_ratio: 150,
        cart_empty_recommend_product_image_fill_type: 'contain',
        social_facebook_link: '',
        social_twitter_link: '',
        social_pinterest_link: '',
        social_instagram_link: '',
        social_snapchat_link: '',
        social_tiktok_link: '',
        social_youtube_link: '',
        social_vimeo_link: '',
        social_tumblr_link: '',
        social_linkedin_link: '',
        social_whatsapp_link: '',
        social_line_link: '',
        social_kakao_link: '',
        favicon_image: '',
        show_official_icon: false,
        show_official_share_icon: false,
        show_social_name: true,
        share_to_facebook: true,
        share_to_twitter: true,
        share_to_pinterest: true,
        share_to_line: true,
        share_to_whatsapp: true,
        share_to_tumblr: true,
        show_breadcrumb: true,
        co_type_title_font: {
          lib: 'system',
          value: 'System',
        },
        co_type_body_font: {
          lib: 'system',
          value: 'System',
        },
        color_scheme_1_gradient: '',
        color_scheme_2_gradient: '',
        color_scheme_3_gradient: '',
        swatch_show_style: 'show_one_row',
        swatch_size: 18,
      },
    },
    {
      type: AriseThemeStyle.Grounded,
      name: 'settings_schema.theme.grounded',
      settings: {
        color_page_background: '#000000',
        color_text: '#ffffff',
        color_light_text: '#fa6400',
        color_sale: '#ffffff',
        color_discount: '#fd500b',
        color_entry_line: '#fd500b',
        color_button_background: '#fd500b',
        color_button_text: '#ffffff',
        color_button_secondary_background: '#000000',
        color_button_secondary_text: '#fd500b',
        color_button_secondary_border: '#fd500b',
        color_discount_tag_background: '#fd500b',
        color_discount_tag_text: '#ffffff',
        color_cart_dot: '#fa6400',
        color_cart_dot_text: '#ffffff',
        color_image_background: '#303030',
        color_image_loading_background: '#fa6400',
        color_mask: '#000000',
        color_scheme_1_bg: '#000000',
        color_scheme_1_text: '#fd500b',
        color_scheme_2_bg: '#000000',
        color_scheme_2_text: '#ffffff',
        color_scheme_3_bg: '#fa6400',
        color_scheme_3_text: '#ffffff',
        title_font_family: 'Anton',
        title_letter_spacing: 50,
        title_font_size: 60,
        title_line_height: 1.2,
        title_uppercase: true,
        body_font_family: 'Poppins',
        body_letter_spacing: 50,
        body_font_size: 14,
        body_line_height: 1.6,
        header_font: 'title',
        header_font_size: 14,
        header_text_uppercase: true,
        page_width: 1920,
        section_vertical_gap: 40,
        grid_horizontal_space: 8,
        grid_vertical_space: 20,
        btn_border_radius: 0,
        btn_border_thickness: 1,
        btn_border_opacity: 100,
        btn_shadow_offset_x: 0,
        btn_shadow_offset_y: 4,
        btn_shadow_blur: 5,
        btn_shadow_opacity: 0,
        input_border_thickness: 1,
        input_border_opacity: 55,
        input_border_radius: 0,
        input_shadow_opacity: 0,
        input_shadow_offset_x: 0,
        input_shadow_offset_y: 4,
        input_shadow_blur: 5,
        sku_selector_border_radius: 0,
        sku_selector_border_thickness: 1,
        sku_selector_border_opacity: 55,
        sku_selector_shadow_opacity: 0,
        sku_selector_shadow_offset_x: 0,
        sku_selector_shadow_offset_y: 4,
        sku_selector_shadow_blur: 5,
        content_border_thickness: 0,
        content_border_opacity: 0,
        content_border_radius: 0,
        content_shadow_opacity: 0,
        content_shadow_offset_x: 0,
        content_shadow_offset_y: 4,
        content_shadow_blur: 5,
        media_border_thickness: 0,
        media_border_opacity: 5,
        media_border_radius: 0,
        media_shadow_opacity: 0,
        media_shadow_offset_x: 0,
        media_shadow_offset_y: 4,
        media_shadow_blur: 5,
        menu_modal_border_thickness: 1,
        menu_modal_border_opacity: 10,
        menu_modal_border_radius: 0,
        menu_modal_shadow_opacity: 0,
        menu_modal_shadow_offset_x: 0,
        menu_modal_shadow_offset_y: 4,
        menu_modal_shadow_blur: 5,
        drawer_border_thickness: 1,
        drawer_border_opacity: 10,
        drawer_shadow_offset_x: 0,
        drawer_shadow_offset_y: 4,
        drawer_shadow_blur: 5,
        drawer_shadow_opacity: 0,
        card_border_thickness: 0,
        card_border_opacity: 10,
        card_border_radius: 0,
        card_shadow_offset_x: 0,
        card_shadow_offset_y: 4,
        card_shadow_blur: 5,
        card_shadow_opacity: 0,
        product_card_border_thickness: 0,
        product_card_border_opacity: 10,
        product_card_border_radius: 0,
        product_card_shadow_offset_x: 0,
        product_card_shadow_offset_y: 0,
        product_card_shadow_blur: 5,
        product_card_shadow_opacity: 0,
        collection_card_border_thickness: 0,
        collection_card_border_opacity: 10,
        collection_card_border_radius: 0,
        collection_card_shadow_offset_x: 0,
        collection_card_shadow_offset_y: 4,
        collection_card_shadow_blur: 5,
        collection_card_shadow_opacity: 0,
        blog_card_border_thickness: 0,
        blog_card_border_opacity: 10,
        blog_card_border_radius: 0,
        blog_card_shadow_offset_x: 0,
        blog_card_shadow_offset_y: 4,
        blog_card_shadow_blur: 5,
        blog_card_shadow_opacity: 0,
        product_discount: true,
        product_discount_tag_style: 'sale',
        product_discount_style: 'number',
        product_add_to_cart_pc_position: 'center',
        enabled_mobile_product_add_to_cart: false,
        product_mobile_quick_add_button_style: 'icon',
        product_discount_position: 'left_bottom',
        product_discount_radius: 0,
        product_card_price_show_type: 'lowest_price',
        product_add_to_cart: true,
        product_card_content_align: 'left',
        enable_quick_view: false,
        product_title_show_type: 'full-display',
        product_mobile_title_show: true,
        enabled_color_swatch: true,
        swatch_max_show: 4,
        swatch_style: 'square',
        cart_type: 'drawer',
        social_facebook_link: '',
        social_twitter_link: '',
        social_pinterest_link: '',
        social_instagram_link: '',
        social_snapchat_link: '',
        social_tiktok_link: '',
        social_youtube_link: '',
        social_linkedin_link: '',
        social_whatsapp_link: '',
        social_line_link: '',
        social_kakao_link: '',
        favicon_image: '',
        show_official_icon: false,
        show_official_share_icon: false,
        show_social_name: true,
        share_to_facebook: true,
        share_to_twitter: true,
        share_to_pinterest: true,
        share_to_line: true,
        share_to_whatsapp: true,
        share_to_tumblr: true,
        show_breadcrumb: true,
        co_type_title_font: {
          lib: 'system',
          value: 'System',
        },
        co_type_body_font: {
          lib: 'system',
          value: 'System',
        },
        color_scheme_1_gradient: '',
        color_scheme_2_gradient: '',
        color_scheme_3_gradient: '',
        swatch_show_style: 'show_one_row',
        swatch_size: 18,
        color_card_background: '',
        color_card_text: '',
        color_link_text: '',
      },
    },
    {
      type: AriseThemeStyle.Hammer,
      name: 'settings_schema.theme.hammer',
      settings: {
        color_page_background: '#ffffff',
        color_text: '#0b1215',
        color_light_text: '#686868',
        color_sale: '#0b1215',
        color_discount: '#EE4700',
        color_entry_line: '#f6f6f6',
        color_button_background: '#ffe46a',
        color_button_text: '#0b1215',
        color_button_secondary_background: '#f6f6f6',
        color_button_secondary_text: '#0b1215',
        color_button_secondary_border: '#f6f6f6',
        color_discount_tag_background: '#ffe46a',
        color_discount_tag_text: '#0b1215',
        color_cart_dot: '#ffe46a',
        color_cart_dot_text: '#0b1215',
        color_image_background: '#fafafa',
        color_image_loading_background: '#f6f6f6',
        color_mask: '#0b1215',
        color_scheme_1_bg: '#ffe46a',
        color_scheme_1_text: '#0b1215',
        color_scheme_2_bg: '#0b1215',
        color_scheme_2_text: '#ffe46a',
        color_scheme_3_bg: '#0b1215',
        color_scheme_3_text: '#ffffff',
        title_font_family: 'Inter:700',
        title_letter_spacing: 0,
        title_font_size: 45,
        title_line_height: 1.2,
        title_uppercase: true,
        body_font_family: 'Inter:regular',
        body_letter_spacing: 50,
        body_font_size: 16,
        body_line_height: 1.3,
        header_font: 'title',
        header_font_size: 14,
        header_text_uppercase: false,
        page_width: 1600,
        section_vertical_gap: 0,
        grid_horizontal_space: 12,
        grid_vertical_space: 12,
        btn_border_radius: 0,
        btn_border_thickness: 1,
        btn_border_opacity: 100,
        btn_shadow_offset_x: 0,
        btn_shadow_offset_y: 2,
        btn_shadow_blur: 0,
        btn_shadow_opacity: 100,
        input_border_thickness: 1,
        input_border_opacity: 10,
        input_border_radius: 0,
        input_shadow_opacity: 0,
        input_shadow_offset_x: 0,
        input_shadow_offset_y: 2,
        input_shadow_blur: 0,
        sku_selector_border_radius: 0,
        sku_selector_border_thickness: 1,
        sku_selector_border_opacity: 55,
        sku_selector_shadow_opacity: 100,
        sku_selector_shadow_offset_x: 0,
        sku_selector_shadow_offset_y: 2,
        sku_selector_shadow_blur: 0,
        content_border_thickness: 1,
        content_border_opacity: 0,
        content_border_radius: 0,
        content_shadow_opacity: 0,
        content_shadow_offset_x: 0,
        content_shadow_offset_y: 4,
        content_shadow_blur: 5,
        media_border_thickness: 0,
        media_border_opacity: 5,
        media_border_radius: 0,
        media_shadow_opacity: 0,
        media_shadow_offset_x: 0,
        media_shadow_offset_y: 4,
        media_shadow_blur: 5,
        menu_modal_border_thickness: 1,
        menu_modal_border_opacity: 10,
        menu_modal_border_radius: 0,
        menu_modal_shadow_opacity: 0,
        menu_modal_shadow_offset_x: 0,
        menu_modal_shadow_offset_y: 4,
        menu_modal_shadow_blur: 5,
        drawer_border_thickness: 1,
        drawer_border_opacity: 10,
        drawer_shadow_offset_x: 0,
        drawer_shadow_offset_y: 4,
        drawer_shadow_blur: 5,
        drawer_shadow_opacity: 0,
        card_border_thickness: 0,
        card_border_opacity: 10,
        card_border_radius: 0,
        card_shadow_offset_x: 0,
        card_shadow_offset_y: 4,
        card_shadow_blur: 5,
        card_shadow_opacity: 0,
        product_card_border_thickness: 0,
        product_card_border_opacity: 10,
        product_card_border_radius: 0,
        product_card_shadow_offset_x: 0,
        product_card_shadow_offset_y: 2,
        product_card_shadow_blur: 0,
        product_card_shadow_opacity: 5,
        collection_card_border_thickness: 0,
        collection_card_border_opacity: 10,
        collection_card_border_radius: 0,
        collection_card_shadow_offset_x: 0,
        collection_card_shadow_offset_y: 2,
        collection_card_shadow_blur: 0,
        collection_card_shadow_opacity: 0,
        blog_card_border_thickness: 0,
        blog_card_border_opacity: 10,
        blog_card_border_radius: 0,
        blog_card_shadow_offset_x: 0,
        blog_card_shadow_offset_y: 0,
        blog_card_shadow_blur: 0,
        blog_card_shadow_opacity: 0,
        product_discount: true,
        product_discount_tag_style: 'save',
        product_discount_style: 'ratio',
        product_add_to_cart_pc_position: 'under',
        enabled_mobile_product_add_to_cart: true,
        product_mobile_quick_add_button_style: 'button',
        product_discount_position: 'right_top',
        product_discount_radius: 40,
        product_card_price_show_type: 'lowest_price',
        product_add_to_cart: true,
        product_card_content_align: 'left',
        enable_quick_view: false,
        product_title_show_type: 'full-display',
        product_mobile_title_show: true,
        enabled_color_swatch: false,
        swatch_max_show: 4,
        swatch_style: 'circle',
        cart_type: 'drawer',
        social_facebook_link: 'https://www.facebook.com/',
        social_twitter_link: 'https://www.x.com/',
        social_pinterest_link: '',
        social_instagram_link: 'https://www.instagram.com/',
        social_snapchat_link: '',
        social_tiktok_link: 'https://www.tiktok.com/',
        social_youtube_link: 'https://www.youtube.com/',
        social_linkedin_link: 'https://www.linkedin.com/',
        social_whatsapp_link: '',
        social_line_link: '',
        social_kakao_link: '',
        favicon_image: '',
        show_official_icon: false,
        show_official_share_icon: false,
        show_social_name: false,
        share_to_facebook: true,
        share_to_twitter: true,
        share_to_pinterest: true,
        share_to_line: true,
        share_to_whatsapp: true,
        share_to_tumblr: true,
        show_breadcrumb: true,
        co_type_title_font: {
          lib: 'system',
          value: 'System',
        },
        co_type_body_font: {
          lib: 'system',
          value: 'System',
        },
        color_scheme_1_gradient: '',
        color_scheme_2_gradient: '',
        color_scheme_3_gradient: '',
        swatch_show_style: 'show_one_row',
        swatch_size: 18,
      },
    },
  ],
};

export default schema;
