import { AriseThemeStyle, ThemeSchemaStruct, WidgetType } from '@/types/section';

const schema: ThemeSchemaStruct = {
  info: {
    name: 'Arise-Pro',
    theme_name: 'Arise-Pro',
    theme_version: '0.0.1',
    theme_author: 'LZC',
    theme_documentation_url: '',
    theme_support_url: '',
    theme_cover_img: '',
    theme_home_pc_preview_img: '',
    theme_home_mobile_preview_img: '',
    theme_pdp_pc_preview_img: '',
    theme_pdp_mobile_preview_img: '',
    theme_type_version: '',
  },
  blocks: [
    {
      name: 'settings_schema.color.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__0.label',
        },
        {
          id: 'color_page_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_page_background.label',
          default: '#FFFFFF',
        },
        {
          id: 'color_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_text.label',
          default: '#29252C',
        },
        {
          id: 'color_light_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_light_text.label',
          default: '#949494',
        },
        {
          id: 'color_entry_line',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_entry_line.label',
          default: '#EAECEC',
        },
        {
          id: 'color_card_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_card_background.label',
          info: 'settings_schema.color.settings.color_card_background.info',
          default: '',
        },
        {
          id: 'color_card_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_card_text.label',
          info: 'settings_schema.color.settings.color_card_text.info',
          default: '',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__1.label',
        },
        {
          id: 'color_button_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_background.label',
          default: '#74716C',
        },
        {
          id: 'color_button_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_text.label',
          default: '#FFFFFF',
        },
        {
          id: 'color_button_secondary_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_secondary_background.label',
          default: '#FFFFFF',
        },
        {
          id: 'color_button_secondary_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_secondary_text.label',
          default: '#74716C',
        },
        {
          id: 'color_button_secondary_border',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_button_secondary_border.label',
          default: '#DDDDDD',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__2.label',
        },
        {
          id: 'color_sale',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_sale.label',
          default: '#171F2B',
        },
        {
          id: 'color_discount',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_discount.label',
          default: '#E32619',
        },
        {
          id: 'color_discount_tag_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_discount_tag_background.label',
          default: '#E32619',
        },
        {
          id: 'color_discount_tag_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_discount_tag_text.label',
          default: '#FFFFFF',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__3.label',
        },
        {
          id: 'color_cart_dot',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_cart_dot.label',
          default: '#74716C',
        },
        {
          id: 'color_cart_dot_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_cart_dot_text.label',
          default: '#FFFFFF',
        },
        {
          id: 'color_image_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_image_background.label',
          default: '#F8F8F8',
        },
        {
          id: 'color_image_loading_background',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_image_loading_background.label',
          default: '#F8F8F8',
        },
        {
          id: 'color_mask',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_mask.label',
          default: '#171717',
        },
        {
          id: 'color_shadow',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_shadow.label',
          default: '',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__4.label',
        },
        {
          id: 'color_scheme_1_bg',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_1_bg.label',
          default: '#FFF8EE',
        },
        {
          id: 'color_scheme_1_gradient',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_1_gradient.label',
          default: '',
        },
        {
          id: 'color_scheme_1_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_1_text.label',
          default: '#2C2924',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__5.label',
        },
        {
          id: 'color_scheme_2_bg',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_2_bg.label',
          default: '#2C2924',
        },
        {
          id: 'color_scheme_2_gradient',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_2_gradient.label',
          default: '',
        },
        {
          id: 'color_scheme_2_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_2_text.label',
          default: '#FFFFFF',
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.color.settings.group_header__6.label',
        },
        {
          id: 'color_scheme_3_bg',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_3_bg.label',
          default: '#F4F7FB',
        },
        {
          id: 'color_scheme_3_gradient',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_3_gradient.label',
          default: '',
        },
        {
          id: 'color_scheme_3_text',
          type: WidgetType.color,
          label: 'settings_schema.color.settings.color_scheme_3_text.label',
          default: '#000000',
        },
      ],
    },
    {
      name: 'settings_schema.font.name',
      settings: [
        {
          type: WidgetType.group_header,
          label: 'settings_schema.font.settings.group_header__0.label',
        },
        {
          id: 'title_font_family',
          type: WidgetType.font,
          label: 'settings_schema.font.settings.title_font_family.label',
          default: 'Assistant:regular',
        },
        {
          id: 'title_letter_spacing',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.title_letter_spacing.label',
          default: 50,
          min: -75,
          max: 250,
          step: 25,
          unit: '%',
        },
        {
          id: 'title_font_size',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.title_font_size.label',
          default: 34,
          min: 22,
          max: 60,
          unit: 'px',
        },
        {
          id: 'title_line_height',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.title_line_height.label',
          default: 1.2,
          min: 0.8,
          max: 2,
          step: 0.1,
        },
        {
          id: 'title_uppercase',
          type: WidgetType.switch,
          label: 'settings_schema.font.settings.title_uppercase.label',
          default: false,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.font.settings.group_header__1.label',
        },
        {
          id: 'body_font_family',
          type: WidgetType.font,
          label: 'settings_schema.font.settings.body_font_family.label',
          default: 'Assistant:regular',
        },
        {
          id: 'body_letter_spacing',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.body_letter_spacing.label',
          default: 50,
          min: -75,
          max: 250,
          step: 25,
          unit: '%',
        },
        {
          id: 'body_font_size',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.body_font_size.label',
          default: 14,
          min: 12,
          max: 20,
          unit: 'px',
        },
        {
          id: 'body_line_height',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.body_line_height.label',
          default: 1.6,
          min: 1,
          max: 2,
          step: 0.1,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.font.settings.group_header__2.label',
        },
        {
          id: 'header_font',
          type: WidgetType.select,
          label: 'settings_schema.font.settings.header_font.label',
          options: [
            {
              value: 'title',
              label: 'settings_schema.font.settings.header_font.options__0.label',
            },
            {
              value: 'body',
              label: 'settings_schema.font.settings.header_font.options__1.label',
            },
          ],
          default: 'body',
        },
        {
          id: 'header_font_size',
          type: WidgetType.range,
          label: 'settings_schema.font.settings.header_font_size.label',
          default: 14,
          min: 12,
          max: 40,
          unit: 'px',
        },
        {
          id: 'header_text_uppercase',
          type: WidgetType.switch,
          label: 'settings_schema.font.settings.header_text_uppercase.label',
          info: 'settings_schema.font.settings.header_text_uppercase.info',
          default: true,
        },
      ],
    },
    {
      name: 'settings_schema.layout.name',
      settings: [
        {
          id: 'page_width',
          type: WidgetType.range,
          label: 'settings_schema.layout.settings.page_width.label',
          min: 1000,
          max: 1920,
          step: 100,
          unit: 'px',
          default: 1400,
        },
        {
          id: 'section_vertical_gap',
          type: WidgetType.range,
          label: 'settings_schema.layout.settings.section_vertical_gap.label',
          min: 0,
          max: 100,
          step: 4,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.layout.settings.group_header__0.label',
          info: 'settings_schema.layout.settings.group_header__0.info',
        },
        {
          id: 'grid_horizontal_space',
          type: WidgetType.range,
          label: 'settings_schema.layout.settings.grid_horizontal_space.label',
          min: 0,
          max: 40,
          step: 4,
          unit: 'px',
          default: 8,
        },
        {
          id: 'grid_vertical_space',
          type: WidgetType.range,
          label: 'settings_schema.layout.settings.grid_vertical_space.label',
          min: 0,
          max: 40,
          step: 4,
          unit: 'px',
          default: 20,
        },
      ],
    },
    {
      name: 'settings_schema.button.name',
      settings: [
        {
          id: 'btn_hover_animation',
          type: WidgetType.select,
          label: 'settings_schema.button.settings.btn_hover_animation.label',
          default: 'hover_zoom',
          options: [
            {
              value: 'light_sweep',
              label: 'settings_schema.button.settings.btn_hover_animation.options__0.label',
            },
            {
              value: 'overlay_projection',
              label: 'settings_schema.button.settings.btn_hover_animation.options__1.label',
            },
            {
              value: 'hover_zoom',
              label: 'settings_schema.button.settings.btn_hover_animation.options__2.label',
            },
            {
              value: 'fill_right',
              label: 'settings_schema.button.settings.btn_hover_animation.options__3.label',
            },
          ],
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.button.settings.group_header__0.label',
        },
        {
          id: 'btn_border_thickness',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_border_thickness.label',
          min: 0,
          max: 12,
          step: 1,
          unit: 'px',
          default: 1,
        },
        {
          id: 'btn_border_opacity',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_border_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 100,
        },
        {
          id: 'btn_border_radius',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_border_radius.label',
          min: 0,
          max: 40,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          type: WidgetType.group_header,
          label: 'settings_schema.button.settings.group_header__1.label',
        },
        {
          id: 'btn_shadow_opacity',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_shadow_opacity.label',
          min: 0,
          max: 100,
          step: 5,
          unit: '%',
          default: 0,
        },
        {
          id: 'btn_shadow_offset_x',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_shadow_offset_x.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 0,
        },
        {
          id: 'btn_shadow_offset_y',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_shadow_offset_y.label',
          min: -12,
          max: 12,
          step: 2,
          unit: 'px',
          default: 4,
        },
        {
          id: 'btn_shadow_blur',
          type: WidgetType.range,
          label: 'settings_schema.button.settings.btn_shadow_blur.label',
          min: 0,
          max: 20,
          step: 5,
          unit: 'px',
          default: 5,
        },
      ],
    },
    {
      name: 'settings_schema.favicon.name',
      settings: [
        {
          id: 'favicon_image',
          type: WidgetType.image_picker,
          label: 'settings_schema.favicon.settings.favicon_image.label',
          info: 'settings_schema.favicon.settings.favicon_image.info',
          default: '',
        },
      ],
    },
  ],
  presets: [
    {
      type: AriseThemeStyle.Default,
      name: 'settings_schema.theme.default',
      settings: {
        color_page_background: '#ffffff',
        color_text: '#3d2f16',
        color_light_text: '#686868',
        color_sale: '#3d2f16',
        color_discount: '#b19460',
        color_entry_line: '#f4f4ef',
        color_card_background: '#f9f9f6',
        color_card_text: '#3d2f16',
        color_button_background: '#b19460',
        color_button_text: '#ffffff',
        color_button_secondary_background: '#ffffff',
        color_button_secondary_text: '#3d2f16',
        color_button_secondary_border: '#3d2f16',
        color_discount_tag_background: '#b19460',
        color_discount_tag_text: '#FFFFFF',
        color_cart_dot: '#b19460',
        color_cart_dot_text: '#FFFFFF',
        color_image_background: '#f4f4ef',
        color_image_loading_background: '#f4f4ef',
        color_mask: '#3d2f16',
        color_scheme_1_bg: '#f4f4ef',
        color_scheme_1_text: '#3d2f16',
        color_scheme_2_bg: '#f4f4ef',
        color_scheme_2_text: '#3d2f16',
        color_scheme_3_bg: '#ebe9d7',
        color_scheme_3_text: '#b19460',
        title_font_family: 'Work Sans:regular',
        title_letter_spacing: 0,
        title_font_size: 60,
        title_line_height: 1.2,
        title_uppercase: true,
        body_font_family: 'Inter:300',
        body_letter_spacing: 25,
        body_font_size: 16,
        body_line_height: 1.6,
        header_font: 'body',
        header_font_size: 16,
        header_text_uppercase: true,
        page_width: 1500,
        section_vertical_gap: 0,
        grid_horizontal_space: 20,
        grid_vertical_space: 20,
        btn_border_radius: 0,
        btn_border_thickness: 1,
        btn_border_opacity: 100,
        btn_shadow_offset_x: 0,
        btn_shadow_offset_y: 4,
        btn_shadow_blur: 5,
        btn_shadow_opacity: 0,

        enable_quick_view: false,
        product_title_show_type: 'full-display',
        product_mobile_title_show: true,
        enabled_color_swatch: true,
        swatch_max_show: 5,
        swatch_style: 'circle',
        cart_type: 'cart_remind',
        cart_empty_recommend_title: 'You May Also Like',
        cart_empty_recommend_collection: '',
        cart_empty_recommend_product_to_show: 6,
        cart_empty_recommend_product_image_ratio: '133.33',
        cart_empty_recommend_product_image_fill_type: 'contain',

        favicon_image: '',
        show_official_icon: false,
        show_official_share_icon: false,
        show_social_name: false,
        share_to_facebook: true,
        share_to_twitter: true,
        share_to_pinterest: true,
        share_to_line: true,
        share_to_whatsapp: true,
        share_to_tumblr: true,
        show_breadcrumb: true,
        co_type_title_font: {
          lib: 'system',
          value: 'System',
        },
        co_type_body_font: {
          lib: 'system',
          value: 'System',
        },
        color_scheme_1_gradient: '',
        color_scheme_2_gradient: '',
        color_scheme_3_gradient: '',
        swatch_show_style: 'show_one_row',
        swatch_size: 18,
        show_search_goods_price: true,
        product_add_to_cart_pc_style: 'button',
        product_pc_title_show: true,
        color_shadow: '',
        btn_hover_animation: 'light_sweep',
      },
    },
    {
      type: AriseThemeStyle.Food,
      name: 'settings_schema.theme.food',
      settings: {
        color_page_background: '#f8edde',
        color_text: '#ff0f00',
        color_light_text: '#529c50',
        color_sale: '#ff0f00',
        color_discount: '#529c50',
        color_entry_line: '#f8edde',
        color_card_background: '',
        color_card_text: '',
        color_button_background: '#ff0f00',
        color_button_text: '#f8edde',
        color_button_secondary_background: '#f8edde',
        color_button_secondary_text: '#ff0f00',
        color_button_secondary_border: '#e02020',
        color_discount_tag_background: '#529c50',
        color_discount_tag_text: '#f8edde',
        color_cart_dot: '#ff0f00',
        color_cart_dot_text: '#f8edde',
        color_image_background: 'rgba(0,0,0,0)',
        color_image_loading_background: '#ff0f00',
        color_mask: '#ff0f00',
        color_shadow: '',
        color_scheme_1_bg: '#ff0f00',
        color_scheme_1_text: '#f8edde',
        color_scheme_2_bg: '#f8edde',
        color_scheme_2_text: '#ff0f00',
        color_scheme_3_bg: '#ff0f00',
        color_scheme_3_text: '#ffe605',
        title_font_family: 'Viaoda Libre',
        title_letter_spacing: 50,
        title_font_size: 60,
        title_line_height: 1.2,
        title_uppercase: false,
        body_font_family: 'Raleway',
        body_letter_spacing: 50,
        body_font_size: 14,
        body_line_height: 1.6,
        header_font: 'title',
        header_font_size: 14,
        header_text_uppercase: true,
        page_width: 1920,
        section_vertical_gap: 0,
        grid_horizontal_space: 8,
        grid_vertical_space: 20,
        btn_border_radius: 0,
        btn_hover_animation: 'hover_zoom',
        btn_border_thickness: 1,
        btn_border_opacity: 100,
        btn_shadow_offset_x: 0,
        btn_shadow_offset_y: 4,
        btn_shadow_blur: 5,
        btn_shadow_opacity: 0,
        input_border_thickness: 1,
        input_border_opacity: 55,
        input_border_radius: 0,
        input_shadow_opacity: 0,
        input_shadow_offset_x: 0,
        input_shadow_offset_y: 4,
        input_shadow_blur: 5,
        sku_selector_border_radius: 0,
        sku_selector_border_thickness: 1,
        sku_selector_border_opacity: 55,
        sku_selector_shadow_opacity: 0,
        sku_selector_shadow_offset_x: 0,
        sku_selector_shadow_offset_y: 4,
        sku_selector_shadow_blur: 5,
        content_border_thickness: 0,
        content_border_opacity: 0,
        content_border_radius: 0,
        content_shadow_opacity: 0,
        content_shadow_offset_x: 0,
        content_shadow_offset_y: 4,
        content_shadow_blur: 5,
        media_border_thickness: 0,
        media_border_opacity: 5,
        media_border_radius: 0,
        media_shadow_opacity: 0,
        media_shadow_offset_x: 0,
        media_shadow_offset_y: 4,
        media_shadow_blur: 5,
        menu_modal_border_thickness: 1,
        menu_modal_border_opacity: 10,
        menu_modal_border_radius: 0,
        menu_modal_shadow_opacity: 0,
        menu_modal_shadow_offset_x: 0,
        menu_modal_shadow_offset_y: 4,
        menu_modal_shadow_blur: 5,
        drawer_border_thickness: 1,
        drawer_border_opacity: 10,
        drawer_shadow_offset_x: 0,
        drawer_shadow_offset_y: 4,
        drawer_shadow_blur: 5,
        drawer_shadow_opacity: 0,
        card_border_thickness: 0,
        card_border_opacity: 10,
        card_border_radius: 0,
        card_shadow_offset_x: 0,
        card_shadow_offset_y: 4,
        card_shadow_blur: 5,
        card_shadow_opacity: 0,
        product_card_style: 'normal',
        product_card_image_padding: 0,
        product_card_border_thickness: 0,
        product_card_border_opacity: 10,
        product_card_border_radius: 0,
        product_card_shadow_offset_x: 0,
        product_card_shadow_offset_y: 0,
        product_card_shadow_blur: 5,
        product_card_shadow_opacity: 0,
        collection_card_style: 'normal',
        collection_card_image_padding: 0,
        collection_card_content_align: 'center',
        collection_card_border_thickness: 0,
        collection_card_border_opacity: 10,
        collection_card_border_radius: 0,
        collection_card_shadow_offset_x: 0,
        collection_card_shadow_offset_y: 4,
        collection_card_shadow_blur: 5,
        collection_card_shadow_opacity: 0,
        blog_card_style: 'normal',
        blog_card_image_padding: 0,
        blog_card_content_align: 'center',
        blog_card_border_thickness: 0,
        blog_card_border_opacity: 10,
        blog_card_border_radius: 0,
        blog_card_shadow_offset_x: 0,
        blog_card_shadow_offset_y: 4,
        blog_card_shadow_blur: 5,
        blog_card_shadow_opacity: 0,
        product_discount: true,
        product_discount_tag_style: 'save',
        product_discount_style: 'number',
        product_add_to_cart_pc_position: 'center',
        product_add_to_cart_pc_style: 'button',
        enabled_mobile_product_add_to_cart: false,
        product_mobile_quick_add_button_style: 'button',
        product_discount_position: 'left_bottom',
        product_discount_radius: 0,
        product_card_price_show_type: 'lowest_price',
        product_add_to_cart: true,
        product_card_content_align: 'left',
        enable_quick_view: true,
        product_title_show_type: 'full-display',
        product_mobile_title_show: true,
        product_pc_title_show: true,
        enabled_color_swatch: false,
        swatch_max_show: 4,
        swatch_style: 'square',
        cart_type: 'drawer',
        cart_empty_recommend_title: 'You May Also Like',
        cart_empty_recommend_collection: '',
        cart_empty_recommend_product_to_show: 12,
        cart_empty_recommend_product_image_ratio: 150,
        cart_empty_recommend_product_image_fill_type: 'contain',
        social_facebook_link: '',
        social_twitter_link: '',
        social_pinterest_link: '',
        social_instagram_link: '',
        social_snapchat_link: '',
        social_tiktok_link: '',
        social_youtube_link: '',
        social_vimeo_link: '',
        social_tumblr_link: '',
        social_linkedin_link: '',
        social_whatsapp_link: '',
        social_line_link: '',
        social_kakao_link: '',
        favicon_image: '',
        show_official_icon: false,
        show_official_share_icon: false,
        show_social_name: true,
        share_to_facebook: true,
        share_to_twitter: true,
        share_to_pinterest: true,
        share_to_line: true,
        share_to_whatsapp: true,
        share_to_tumblr: true,
        show_breadcrumb: true,
        co_type_title_font: {
          lib: 'system',
          value: 'System',
        },
        co_type_body_font: {
          lib: 'system',
          value: 'System',
        },
        color_scheme_1_gradient: '',
        color_scheme_2_gradient: '',
        color_scheme_3_gradient: '',
        swatch_show_style: 'show_one_row',
        swatch_size: 18,
      },
    },
    {
      type: AriseThemeStyle.Grounded,
      name: 'settings_schema.theme.grounded',
      settings: {
        color_page_background: '#000000',
        color_text: '#ffffff',
        color_light_text: '#fa6400',
        color_sale: '#ffffff',
        color_discount: '#fd500b',
        color_entry_line: '#fd500b',
        color_button_background: '#fd500b',
        color_button_text: '#ffffff',
        color_button_secondary_background: '#000000',
        color_button_secondary_text: '#fd500b',
        color_button_secondary_border: '#fd500b',
        color_discount_tag_background: '#fd500b',
        color_discount_tag_text: '#ffffff',
        color_cart_dot: '#fa6400',
        color_cart_dot_text: '#ffffff',
        color_image_background: '#303030',
        color_image_loading_background: '#fa6400',
        color_mask: '#000000',
        color_scheme_1_bg: '#000000',
        color_scheme_1_text: '#fd500b',
        color_scheme_2_bg: '#000000',
        color_scheme_2_text: '#ffffff',
        color_scheme_3_bg: '#fa6400',
        color_scheme_3_text: '#ffffff',
        title_font_family: 'Anton',
        title_letter_spacing: 50,
        title_font_size: 60,
        title_line_height: 1.2,
        title_uppercase: true,
        body_font_family: 'Poppins',
        body_letter_spacing: 50,
        body_font_size: 14,
        body_line_height: 1.6,
        header_font: 'title',
        header_font_size: 14,
        header_text_uppercase: true,
        page_width: 1920,
        section_vertical_gap: 40,
        grid_horizontal_space: 8,
        grid_vertical_space: 20,
        btn_border_radius: 0,
        btn_border_thickness: 1,
        btn_border_opacity: 100,
        btn_shadow_offset_x: 0,
        btn_shadow_offset_y: 4,
        btn_shadow_blur: 5,
        btn_shadow_opacity: 0,
        input_border_thickness: 1,
        input_border_opacity: 55,
        input_border_radius: 0,
        input_shadow_opacity: 0,
        input_shadow_offset_x: 0,
        input_shadow_offset_y: 4,
        input_shadow_blur: 5,
        sku_selector_border_radius: 0,
        sku_selector_border_thickness: 1,
        sku_selector_border_opacity: 55,
        sku_selector_shadow_opacity: 0,
        sku_selector_shadow_offset_x: 0,
        sku_selector_shadow_offset_y: 4,
        sku_selector_shadow_blur: 5,
        content_border_thickness: 0,
        content_border_opacity: 0,
        content_border_radius: 0,
        content_shadow_opacity: 0,
        content_shadow_offset_x: 0,
        content_shadow_offset_y: 4,
        content_shadow_blur: 5,
        media_border_thickness: 0,
        media_border_opacity: 5,
        media_border_radius: 0,
        media_shadow_opacity: 0,
        media_shadow_offset_x: 0,
        media_shadow_offset_y: 4,
        media_shadow_blur: 5,
        menu_modal_border_thickness: 1,
        menu_modal_border_opacity: 10,
        menu_modal_border_radius: 0,
        menu_modal_shadow_opacity: 0,
        menu_modal_shadow_offset_x: 0,
        menu_modal_shadow_offset_y: 4,
        menu_modal_shadow_blur: 5,
        drawer_border_thickness: 1,
        drawer_border_opacity: 10,
        drawer_shadow_offset_x: 0,
        drawer_shadow_offset_y: 4,
        drawer_shadow_blur: 5,
        drawer_shadow_opacity: 0,
        card_border_thickness: 0,
        card_border_opacity: 10,
        card_border_radius: 0,
        card_shadow_offset_x: 0,
        card_shadow_offset_y: 4,
        card_shadow_blur: 5,
        card_shadow_opacity: 0,
        product_card_border_thickness: 0,
        product_card_border_opacity: 10,
        product_card_border_radius: 0,
        product_card_shadow_offset_x: 0,
        product_card_shadow_offset_y: 0,
        product_card_shadow_blur: 5,
        product_card_shadow_opacity: 0,
        collection_card_border_thickness: 0,
        collection_card_border_opacity: 10,
        collection_card_border_radius: 0,
        collection_card_shadow_offset_x: 0,
        collection_card_shadow_offset_y: 4,
        collection_card_shadow_blur: 5,
        collection_card_shadow_opacity: 0,
        blog_card_border_thickness: 0,
        blog_card_border_opacity: 10,
        blog_card_border_radius: 0,
        blog_card_shadow_offset_x: 0,
        blog_card_shadow_offset_y: 4,
        blog_card_shadow_blur: 5,
        blog_card_shadow_opacity: 0,
        product_discount: true,
        product_discount_tag_style: 'sale',
        product_discount_style: 'number',
        product_add_to_cart_pc_position: 'center',
        enabled_mobile_product_add_to_cart: false,
        product_mobile_quick_add_button_style: 'icon',
        product_discount_position: 'left_bottom',
        product_discount_radius: 0,
        product_card_price_show_type: 'lowest_price',
        product_add_to_cart: true,
        product_card_content_align: 'left',
        enable_quick_view: false,
        product_title_show_type: 'full-display',
        product_mobile_title_show: true,
        enabled_color_swatch: true,
        swatch_max_show: 4,
        swatch_style: 'square',
        cart_type: 'drawer',
        social_facebook_link: '',
        social_twitter_link: '',
        social_pinterest_link: '',
        social_instagram_link: '',
        social_snapchat_link: '',
        social_tiktok_link: '',
        social_youtube_link: '',
        social_linkedin_link: '',
        social_whatsapp_link: '',
        social_line_link: '',
        social_kakao_link: '',
        favicon_image: '',
        show_official_icon: false,
        show_official_share_icon: false,
        show_social_name: true,
        share_to_facebook: true,
        share_to_twitter: true,
        share_to_pinterest: true,
        share_to_line: true,
        share_to_whatsapp: true,
        share_to_tumblr: true,
        show_breadcrumb: true,
        co_type_title_font: {
          lib: 'system',
          value: 'System',
        },
        co_type_body_font: {
          lib: 'system',
          value: 'System',
        },
        color_scheme_1_gradient: '',
        color_scheme_2_gradient: '',
        color_scheme_3_gradient: '',
        swatch_show_style: 'show_one_row',
        swatch_size: 18,
        color_card_background: '',
        color_card_text: '',
        color_link_text: '',
      },
    },
    {
      type: AriseThemeStyle.Hammer,
      name: 'settings_schema.theme.hammer',
      settings: {
        color_page_background: '#ffffff',
        color_text: '#0b1215',
        color_light_text: '#686868',
        color_sale: '#0b1215',
        color_discount: '#EE4700',
        color_entry_line: '#f6f6f6',
        color_button_background: '#ffe46a',
        color_button_text: '#0b1215',
        color_button_secondary_background: '#f6f6f6',
        color_button_secondary_text: '#0b1215',
        color_button_secondary_border: '#f6f6f6',
        color_discount_tag_background: '#ffe46a',
        color_discount_tag_text: '#0b1215',
        color_cart_dot: '#ffe46a',
        color_cart_dot_text: '#0b1215',
        color_image_background: '#fafafa',
        color_image_loading_background: '#f6f6f6',
        color_mask: '#0b1215',
        color_scheme_1_bg: '#ffe46a',
        color_scheme_1_text: '#0b1215',
        color_scheme_2_bg: '#0b1215',
        color_scheme_2_text: '#ffe46a',
        color_scheme_3_bg: '#0b1215',
        color_scheme_3_text: '#ffffff',
        title_font_family: 'Inter:700',
        title_letter_spacing: 0,
        title_font_size: 45,
        title_line_height: 1.2,
        title_uppercase: true,
        body_font_family: 'Inter:regular',
        body_letter_spacing: 50,
        body_font_size: 16,
        body_line_height: 1.3,
        header_font: 'title',
        header_font_size: 14,
        header_text_uppercase: false,
        page_width: 1600,
        section_vertical_gap: 0,
        grid_horizontal_space: 12,
        grid_vertical_space: 12,
        btn_border_radius: 0,
        btn_border_thickness: 1,
        btn_border_opacity: 100,
        btn_shadow_offset_x: 0,
        btn_shadow_offset_y: 2,
        btn_shadow_blur: 0,
        btn_shadow_opacity: 100,
        input_border_thickness: 1,
        input_border_opacity: 10,
        input_border_radius: 0,
        input_shadow_opacity: 0,
        input_shadow_offset_x: 0,
        input_shadow_offset_y: 2,
        input_shadow_blur: 0,
        sku_selector_border_radius: 0,
        sku_selector_border_thickness: 1,
        sku_selector_border_opacity: 55,
        sku_selector_shadow_opacity: 100,
        sku_selector_shadow_offset_x: 0,
        sku_selector_shadow_offset_y: 2,
        sku_selector_shadow_blur: 0,
        content_border_thickness: 1,
        content_border_opacity: 0,
        content_border_radius: 0,
        content_shadow_opacity: 0,
        content_shadow_offset_x: 0,
        content_shadow_offset_y: 4,
        content_shadow_blur: 5,
        media_border_thickness: 0,
        media_border_opacity: 5,
        media_border_radius: 0,
        media_shadow_opacity: 0,
        media_shadow_offset_x: 0,
        media_shadow_offset_y: 4,
        media_shadow_blur: 5,
        menu_modal_border_thickness: 1,
        menu_modal_border_opacity: 10,
        menu_modal_border_radius: 0,
        menu_modal_shadow_opacity: 0,
        menu_modal_shadow_offset_x: 0,
        menu_modal_shadow_offset_y: 4,
        menu_modal_shadow_blur: 5,
        drawer_border_thickness: 1,
        drawer_border_opacity: 10,
        drawer_shadow_offset_x: 0,
        drawer_shadow_offset_y: 4,
        drawer_shadow_blur: 5,
        drawer_shadow_opacity: 0,
        card_border_thickness: 0,
        card_border_opacity: 10,
        card_border_radius: 0,
        card_shadow_offset_x: 0,
        card_shadow_offset_y: 4,
        card_shadow_blur: 5,
        card_shadow_opacity: 0,
        product_card_border_thickness: 0,
        product_card_border_opacity: 10,
        product_card_border_radius: 0,
        product_card_shadow_offset_x: 0,
        product_card_shadow_offset_y: 2,
        product_card_shadow_blur: 0,
        product_card_shadow_opacity: 5,
        collection_card_border_thickness: 0,
        collection_card_border_opacity: 10,
        collection_card_border_radius: 0,
        collection_card_shadow_offset_x: 0,
        collection_card_shadow_offset_y: 2,
        collection_card_shadow_blur: 0,
        collection_card_shadow_opacity: 0,
        blog_card_border_thickness: 0,
        blog_card_border_opacity: 10,
        blog_card_border_radius: 0,
        blog_card_shadow_offset_x: 0,
        blog_card_shadow_offset_y: 0,
        blog_card_shadow_blur: 0,
        blog_card_shadow_opacity: 0,
        product_discount: true,
        product_discount_tag_style: 'save',
        product_discount_style: 'ratio',
        product_add_to_cart_pc_position: 'under',
        enabled_mobile_product_add_to_cart: true,
        product_mobile_quick_add_button_style: 'button',
        product_discount_position: 'right_top',
        product_discount_radius: 40,
        product_card_price_show_type: 'lowest_price',
        product_add_to_cart: true,
        product_card_content_align: 'left',
        enable_quick_view: false,
        product_title_show_type: 'full-display',
        product_mobile_title_show: true,
        enabled_color_swatch: false,
        swatch_max_show: 4,
        swatch_style: 'circle',
        cart_type: 'drawer',
        social_facebook_link: 'https://www.facebook.com/',
        social_twitter_link: 'https://www.x.com/',
        social_pinterest_link: '',
        social_instagram_link: 'https://www.instagram.com/',
        social_snapchat_link: '',
        social_tiktok_link: 'https://www.tiktok.com/',
        social_youtube_link: 'https://www.youtube.com/',
        social_linkedin_link: 'https://www.linkedin.com/',
        social_whatsapp_link: '',
        social_line_link: '',
        social_kakao_link: '',
        favicon_image: '',
        show_official_icon: false,
        show_official_share_icon: false,
        show_social_name: false,
        share_to_facebook: true,
        share_to_twitter: true,
        share_to_pinterest: true,
        share_to_line: true,
        share_to_whatsapp: true,
        share_to_tumblr: true,
        show_breadcrumb: true,
        co_type_title_font: {
          lib: 'system',
          value: 'System',
        },
        co_type_body_font: {
          lib: 'system',
          value: 'System',
        },
        color_scheme_1_gradient: '',
        color_scheme_2_gradient: '',
        color_scheme_3_gradient: '',
        swatch_show_style: 'show_one_row',
        swatch_size: 18,
      },
    },
  ],
};

export default schema;
